### ISSUE TITLE
@unthrown/oxlint@5.0.0-beta.10 raises the oxlint peer to ^1.74.0 despite a byte-identical plugin bundle

### ISSUE THREAD

**Issue by btravers** [btravstack/unthrown#163]
## Summary

`@unthrown/oxlint@5.0.0-beta.10` raised its oxlint peer range, but ships a plugin implementation that is **byte-identical** to beta.9 (which requires `^1.69.0`). The tighter range looks unintentional, and it is expensive for consumers.

```diff
 "peerDependencies": {
-  "oxlint": "^1.69.0"
+  "oxlint": "^1.74.0"
 }
```

## Evidence the code did not change

Comparing the two published tarballs, the only differences in `dist/index.mjs` are a dropped `sourceMappingURL` comment and one blank line:

```console
$ diff <(grep -v sourceMappingURL beta.9/dist/index.mjs) <(grep -v sourceMappingURL beta.10/dist/index.mjs)
545d544
<
```

`dist/index.d.mts` differs only by the same dropped sourcemap comment. The only oxlint plugin APIs the bundle touches are `context.report`, `context.sourceCode` and `getScope` — all present and stable in 1.69.

## Evidence it works on 1.69 at runtime

I installed `@unthrown/oxlint@5.0.0-beta.10` against `oxlint@1.69.0` / `oxlint-tsgolint@0.23.0` (pnpm resolved it as `@unthrown+oxlint@5.0.0-beta.10_oxlint@1.69.0_oxlint-tsgolint@0.23.0_`) and all four `recommended` rules fire correctly:

```console
probe.ts:5:50: error unthrown(no-ambiguous-error-type): Specify a concrete domain error instead of `unknown` in `AsyncResult<number, unknown>`.
probe.ts:9:34: error unthrown(prefer-async-result): Use `AsyncResult<T, E>` instead of `Promise<Result<T, E>>`.
probe.ts:13:77: error unthrown(no-ambiguous-error-type): Specify a concrete domain error instead of `Error` in `AsyncResult<number, Error>`.
probe.ts:14:50: error unthrown(no-catch-all-pattern): Unexpected `P._` catch-all. …
probe2.ts:6:3:  error unthrown(no-unhandled-result): The `Result` returned by `fromSafePromise` is dropped …
probe2.ts:7:9:  error unthrown(no-unhandled-result): …
probe2.ts:8:3:  error unthrown(no-unhandled-result): The `Result` returned by `Ok` is dropped …
```

A full repo lint (265 projects) with all four rules at `error` also ran clean, exit 0. I did not find a behavioural difference between the two versions on 1.69.

## Why the range matters downstream

With `strictPeerDependencies: true`, `^1.74.0` fails `pnpm install` outright, and satisfying it cascades:

| Step | Constraint |
| --- | --- |
| `@unthrown/oxlint@5.0.0-beta.10` | needs `oxlint >= 1.74.0` |
| `oxlint@1.74.0` | needs `oxlint-tsgolint >= 0.24.0` |

`oxlint-tsgolint` is the engine behind `oxlint --type-aware --type-check`, so adopting a *packaging-only* plugin release drags a lint **and** typecheck engine upgrade (5 oxlint minors + a tsgolint bump) across every project in the monorepo at once.

There is also a supply-chain angle: our install enforces a 14-day `minimumReleaseAge`. At the time of writing, `1.74.0` is the only release that both satisfies `^1.74.0` and has cleared the window (1.75.0 and 1.76.0 are still quarantined), so the range effectively pins consumers to one specific version rather than giving them a choice.

We ended up holding the plugin at beta.9 while taking `unthrown` / `@unthrown/vitest` / `@unthrown/prisma` to the latest betas.

## Suggestion

If nothing in the plugin actually requires 1.74, relax the peer back to `^1.69.0` (or whatever the true floor is) so the range tracks a real API requirement rather than the version that happened to be current at publish time. If something *does* require it, it would help to note it in the release notes — the identical bundle made it look accidental from the outside.

Happy to test a `beta.11` against 1.69 if useful.
