### PR TITLE
fix(oxlint): restore the oxlint peer floor to ^1.69.0

### LINKED ISSUE #163: @unthrown/oxlint@5.0.0-beta.10 raises the oxlint peer to ^1.74.0 despite a byte-identical plugin bundle
## Summary

`@unthrown/oxlint@5.0.0-beta.10` raised its oxlint peer range, but ships a plugin implementation that is **byte-identical** to beta.9 (which requires `^1.69.0`). The tighter range looks unintentional, and it is expensive for consumers.

```diff
 "peerDependencies": {
-  "oxlint": "^1.69.0"
+  "oxlint": "^1.74.0"
 }
```

## Evidence the code did not change

Comparing the two published tarballs, the only differences in `dist/index.mjs` are a dropped `sourceMappingURL` comment and one blank line:

```console
$ diff <(grep -v sourceMappingURL beta.9/dist/index.mjs) <(grep -v sourceMappingURL beta.10/dist/index.mjs)
545d544
<
```

`dist/index.d.mts` differs only by the same dropped sourcemap comment. The only oxlint plugin APIs the bundle touches are `context.report`, `context.sourceCode` and `getScope` — all present and stable in 1.69.

## Evidence it works on 1.69 at runtime

I installed `@unthrown/oxlint@5.0.0-beta.10` against `oxlint@1.69.0` / `oxlint-tsgolint@0.23.0` (pnpm resolved it as `@unthrown+oxlint@5.0.0-beta.10_oxlint@1.69.0_oxlint-tsgolint@0.23.0_`) and all four `recommended` rules fire correctly:

```console
probe.ts:5:50: error unthrown(no-ambiguous-error-type): Specify a concrete domain error instead of `unknown` in `AsyncResult<number, unknown>`.
probe.ts:9:34: error unthrown(prefer-async-result): Use `AsyncResult<T, E>` instead of `Promise<Result<T, E>>`.
probe.ts:13:77: error unthrown(no-ambiguous-error-type): Specify a concrete domain error instead of `Error` in `AsyncResult<number, Error>`.
probe.ts:14:50: error unthrown(no-catch-all-pattern): Unexpected `P._` catch-all. …
probe2.ts:6:3:  error unthrown(no-unhandled-result): The `Result` returned by `fromSafePromise` is dropped …
probe2.ts:7:9:  error unthrown(no-unhandled-result): …
probe2.ts:8:3:  error unthrown(no-unhandled-result): The `Result` returned by `Ok` is dropped …
```

A full repo lint (265 projects) with all four rules at `error` also ran clean, exit 0. I did not find a behavioural difference between the two versions on 1.69.

## Why the range matters downstream

With `strictPeerDependencies: true`, `^1.74.0` fails `pnpm install` outright, and satisfying it cascades:

| Step | Constraint |
| --- | --- |
| `@unthrown/oxlint@5.0.0-beta.10` | needs `oxlint >= 1.74.0` |
| `oxlint@1.74.0` | needs `oxlint-tsgolint >= 0.24.0` |

`oxlint-tsgolint` is the engine behind `oxlint --type-aware --type-check`, so adopting a *packaging-only* plugin release drags a lint **and** typecheck engine upgrade (5 oxlint minors + a tsgolint bump) across every project in the monorepo at once.

There is also a supply-chain angle: our install enforces a 14-day `minimumReleaseAge`. At the time of writing, `1.74.0` is the only release that both satisfies `^1.74.0` and has cleared the window (1.75.0 and 1.76.0 are still quarantined), so the range effectively pins consumers to one specific version rather than giving them a choice.

We ended up holding the plugin at beta.9 while taking `unthrown` / `@unthrown/vitest` / `@unthrown/prisma` to the latest betas.

## Suggestion

If nothing in the plugin actually requires 1.74, relax the peer back to `^1.69.0` (or whatever the true floor is) so the range tracks a real API requirement rather than the version that happened to be current at publish time. If something *does* require it, it would help to note it in the release notes — the identical bundle made it look accidental from the outside.

Happy to test a `beta.11` against 1.69 if useful.

### PR DESCRIPTION
**Pull request by btravers**
Closes #163.

## The bump was mechanical

`@unthrown/oxlint@5.0.0-beta.10` raised its `oxlint` peer from `^1.69.0` to `^1.74.0` while shipping a plugin bundle byte-identical to beta.9's (bar a dropped sourcemap comment). Tracing it back:

- `fd40735` set `^1.69.0` deliberately — *"oxlint JS plugins require >=1.69"*.
- `6c8cb55` (dependabot) took the **`@oxlint/plugins` dependency** 1.73 → 1.74.
- `92c848b` (the pre-v5-stable audit) then raised the **peer** to `^1.74.0` *"matching the `@oxlint/plugins` runtime the rules are built against"*.

So the floor got slaved to a version a bot bumps on its own cadence, not to any host API the rules need. The package README and `docs/how-to/lint-your-codebase.md` were never updated and still say ≥ 1.69 — consistent again after this revert.

## Verified against real hosts

The bundle only touches `context.report` (with `fix`), `context.sourceCode`, `getScope`, and `defineConfig` from `oxlint`. No suggestion API is used — the `suggest` hits in the source are `meta.type: "suggestion"`.

Built the plugin and ran it against real oxlint hosts, with `@oxlint/plugins` held at 1.74.0 (the realistic consumer tree, since that dependency is unchanged here):

| host | diagnostics | `prefer-async-result` autofix |
| --- | --- | --- |
| 1.69.0 | 6/6 rules fire | applies |
| 1.74.0 | 6/6 rules fire | applies |
| 1.76.0 | 6/6 rules fire | applies |

## Why the range mattered downstream

Per the issue: under `strictPeerDependencies` `^1.74.0` fails `pnpm install` outright, and satisfying it cascades into `oxlint@1.74.0` → `oxlint-tsgolint@0.24.0` — a lint **and** type-check engine upgrade across every consuming project, for a packaging-only release. A 14-day `minimumReleaseAge` also left 1.74.0 as the only version both satisfying the range and out of quarantine, effectively pinning consumers to one version.

## Changes

- `packages/oxlint/package.json` — peer `oxlint` back to `^1.69.0`.
- `packages/oxlint/src/index.test.ts` — regression guard pinning the floor, with the reasoning inline so the next mechanical bump fails CI instead of shipping.
- `packages/oxlint/tsconfig.json` — `"types": ["node"]` (mirrors core's), for the manifest read in that test.
- `CLAUDE.md` — records the rule: the peer floor names the oldest verified *host*, decoupled from the `@oxlint/plugins` dependency; raise it only when a rule starts using a host API that needs it, and name that API in the changeset.
- `.changeset/relax-oxlint-peer-floor.md` — patch changeset.

## Notes

- The `@oxlint/plugins` **dependency** stays at `^1.74.0`. It is an ordinary dependency, so it cannot fail a consumer's install, and 1.74's compat shim is exactly what was verified against a 1.69 host.
- 1.69 is not a hard API boundary — hosts down to 1.50.0 also run the plugin in a sweep. `^1.69.0` is restored rather than lowered further because it is the range the package shipped with for its whole life before beta.10: a strict de-restriction, no new support claim.

Gate green locally: `format --check`, `lint`, `typecheck`, `knip`, `test`, `build`, plus `pnpm install --frozen-lockfile` (the lockfile is unaffected).

🤖 Generated with [Claude Code](https://claude.com/claude-code)

### CODE REVIEW

File: packages/oxlint/package.json [hunk 1]
```diff
@@ -62,7 +62,7 @@
     "vitest": "catalog:"
   },
   "peerDependencies": {
-    "oxlint": "^1.74.0"
+    "oxlint": "^1.69.0"
```
Comment (btravers) [inline packages/oxlint/package.json:65]: should we consider using a greater than operator?

Comment (btravers) [reply packages/oxlint/package.json:65]: My recommendation is to keep the caret, but here is the reasoning so you can overrule it.

`^1.69.0` is `>=1.69.0 <2.0.0`. Switching to `>=1.69.0` only changes one thing: it drops the major ceiling. It does nothing for the problem #163 reported — that was an over-tight *floor*, and the floor is identical either way.

What the ceiling is doing: the surface this plugin binds to is exactly what an oxlint major would break — `defineConfig` imported from `oxlint` itself, the `jsPlugins` config shape, `eslintCompatPlugin`'s host contract, and `context.sourceCode.getScope`. With `>=`, an oxlint 2.0 would install cleanly and then fail at lint time with whatever error a changed plugin loader produces. With `^`, the consumer gets a peer conflict at install — an accurate signal that the combination is unverified, and one we can clear in a patch release once we've actually run the rules against 2.0.

It is also the only unbounded peer we would have; every other package in the repo caps the major (`effect: ^3`, `neverthrow: ^8`, `@prisma/client: ^7`, `@bloodyowl/boxed: ^3`, `vitest: ^4`, `@orpc/*: ^2.0.0-beta`).

When oxlint 2.0 lands, the deliberate move is to widen to `^1.69.0 || ^2.0.0` after verifying the rules on it — which is the same "raise/widen only against a verified host" policy this PR writes down for the floor.

The honest counterargument is churn: with the caret, consumers are blocked on us publishing a widened range after every oxlint major. Given oxlint has had exactly one major so far and a patch release is cheap here, I think that trade favours the ceiling — but say the word and I'll switch it to `>=1.69.0`.
